### PR TITLE
support language column

### PR DESCRIPTION
**Pull request by gillax**
I added 'language_column' to set member's language. it's optional but I need.

### CODE REVIEW

**Comment by gillax** [comment]
Travis failed, but using openjdk 8 will go well. It probably is due to the version of openjdk.

**Comment by sakama** [comment]
Thanks for PR and it looks good to me.
I'm fixing CI failure at #33.

**Comment by sakama** [comment]
@thangnc Do you have any concern about this PR?
If nothing, I'll merge this PR and release new version.
CI failure will be fixed by #33

**Comment by thangnc** [comment]
@sakama this PR looks good to me

**Review by thangnc — APPROVED** [review]

**Comment by sakama** [comment]
@gillax We released as v0.3.17
https://rubygems.org/gems/embulk-output-mailchimp
https://github.com/treasure-data/embulk-output-mailchimp/blob/master/CHANGELOG.md

Thanks for your contributing 👍

**Pull request merged**
