### PR TITLE
Enable double optin

### PR DESCRIPTION
**Pull request by thangnc**
- Follows PR https://github.com/treasure-data/embulk-output-mailchimp/pull/13
- Restore `double_optin` from configuration
- Use default `status` with `double_optin` if schema has no column `status`
- Use data center info extract from metadata url

### CODE REVIEW

**Comment by sakama** [comment]
Let's merge #13 first, and  organize #15 and #16.
Both PRs contains huge diff and difficult to understand what PR intended of.

**Comment by thangnc** [comment]
@sakama ok, then im going to merge #13 first

**Comment by thangnc** [comment]
@sakama PTAL

**Review by sakama — APPROVED** [review]
LGTM

**Pull request merged**
